name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        ${{ if true}}:
          run: echo Hello, world!
        ${{ if false}}:
          run: echo Hello, mars
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
