name: first CI

on:
  push:
    branches: [ none ]

  workflow_dispatch:
    inputs:
      folderToLL:
        required: false
        default: 'tmp'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        if: ${{ 10 == 10 }}
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: ls steps
        run: ls -al
        working-directory: ${{ inputs.folderToLL == 'tmp' && './temp' || github.workspace }}
