name: Python 3.x


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: 3.8
    - name: Instal Python Package
      run: pip3 install requests
    - name: Prepare the python script
      shell: python
      run: |
        import requests
        import json
        api='${{ github.api_url }}/users/${{ github.actor }}/packages/container/${{ github.event.repository.name }}/versions'
        r=requests.get(api, auth=('${{ github.actor }}','${{ secrets.GITHUB_TOKEN }}'))
        if(r.status_code == 200):
            v = json.loads(r.text)
            print(v[0]['metadata']['container']['tags'][0])
        else:
            print('Something went wrong')
