
name: Workflow Event
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_run:
    workflows: [ "Simple Workflow" ]
    branches:
    - main
    types:
    - completed
    
  workflow_dispatch:
    inputs:
      deployEnv:
        description: Deployable Env
        type: environment
      name:
        description: Name
        type: sring
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo WorkFlow Event Name : ${{ github.event_name }}
          echo Deploy Env: ${{ inputs.deployEnv }} / ${{ github.event.inputs.deployEnv }}
          echo Name : ${{ inputs.name }} / ${{ github.event.inputs.name }}
  dev:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.deployEnv == 'dev' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo I am in dev
          echo WorkFlow Event Name : ${{ github.event_name }}

  prod:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.deployEnv == 'prod' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo I am in prod
          echo WorkFlow Event Name : ${{ github.event_name }}
