# This is a basic workflow to help you get started with Actions

name: Composite Workflow
on:
  push:
    branches: [ none ]
  create:
    tags: 
    - '*'
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hi
        if: ${{ 5 == 2 }}
        name: message with condition
        shell: bash
      - uses: ./.github/composite/test
        with: 
          name: samit
