name: Debug Pipeline

on:
  workflow_dispatch:
    inputs:
      display:
        description: Display Conditional Steps ?
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Github Script
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context)
          console.log("##############")
          console.log(context.payload)
    - name: conditional step
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || inputs.display
      run: echo 'Hello I am executing'
