# This is a basic workflow to help you get started with Actions

name: Github Script
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const clusters = github.request('./.github/metadata/cluster.json').then((response) => response.json())
            console.log(clusters)
