name: Capture Events

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Event Name
      run: echo ${{ github.event_name }}
    - name: Event Details
      run: 'echo ${{ fromJson(github) }}'
