name: Output Example
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          echo "::set-output name=test::hello"
          echo "HELLO=yea loo" >> $GITHUB_ENV
          echo "action_state=yellow" >> $GITHUB_ENV
      - id: step2
        run: |
          echo "::set-output name=test::world"
          echo "HELLO=${{ env.HELLO }}"
          echo "${{ env.action_state }}" 
      - id: echo
        run: |
          echo "steps.step1.test= ${{ steps.step1.test }}"
          echo "steps.step2.test= ${{ steps.step2.test }}"
          echo "$HELLO" $HELLO
          echo "${{ env.action_state }}" 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: |
        echo ${{needs.job1.outputs.output1}} 
        echo ${{needs.job1.outputs.output2}}
        echo "HELLO=${{env.HELLO}}"
        echo $HELLO
        env
