name: Output Example One

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.shell_output_key_value.outputs.custom_stdout }}
      output2: ${{ steps.shell_output.outputs.stdout }}
      output3: ${{ steps.mvn_output.outputs.m_output }}
    steps:
    - name: Shell Output Key Value
      id: shell_output_key_value
      run: echo "custom_stdout=Hello World from shell_output_key_value" >> $GITHUB_OUTPUT
    - name: Shell Output
      id: shell_output
      run: echo "Hello World Without Key Value"
    - name: Maven Shell Output
      continue-on-error: true
      id: mvn_output
      run: |
        mvn --log-file mvnoutfile --version
        echo "m_output=$(cat -s mvnoutfile)" >> $GITHUB_OUTPUT
  print_output:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: output1 
      run: echo ${{ needs.build.outputs.output1 }}
    - name: output2
      run: echo ${{ needs.build.outputs.output2 }}
    - name: output3
      continue-on-error: true
      run: echo ${{ needs.build.outputs.output3 }}
    - name: gh
      run: gh run view --log $GITHUB_RUN_ID
