name: Output Example One

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.shell_output.outputs.stdout }}
    steps:
    - name: Shell Output
      id: shell_output
      run: echo "stdout=Hello World from shell_output" >> $GITHUB_OUTPUT
  print_output:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Shell Output Print
      run: echo ${{ needs.build.outputs.output1 }}
