name: Trigger Auto when Publish Package 
on:
  registry_package:
    types: [published, updated]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Package Info
      run: |
        echo 'Under Construction'
    - run: 'echo "field: ${{ github.event.client_payload.foo }}"'
    - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
