name: Reusable Deploy Workflow
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true
   
jobs:
  prepare:
    name: Prepare ${{ inputs.username }}
    runs-on: ubuntu-latest
    steps:
    - name: print
      run: echo ${{ inputs.username }} invoke deployment for ${{ inputs.environment }}
  deployment:
    name: Deploy ${{ inputs.environment }}
    needs: prepare
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo ${{ inputs.environment }} completed!
               
