name: Reusable Deploy Workflow
on:
  workflow_call:
    inputs:
      dockerImage:
        description: 'Docker Image Name'
        type: string
        required: false
      dockerImageVersion:
        description: 'Docker Image Version'
        type: string
        required: true
      deployEnvironment:
        description: 'Deployment Environment'
        type: string
        required: true
   
jobs:
  deployment-information:
    runs-on: ubuntu-latest
    steps:
    - name: Information
      uses: actions/github-script@v6
      id: information
      with:
        #result-encoding: string
        script: |
          console.log(context)
          console.log(`Workflow Inputs are : ${ context?.payload?.inputs }`)
  deploy-env:
    runs-on: ubuntu-latest
    needs: deployment-information
    strategy:
      matrix:
        targetEnv : ['dev','preprod']
    steps:
    - name: steps level matrix - ${{ matrix.targetEnv }}
      run: echo Target Environment is ${{ matrix.targetEnv }}
      
        
        
               
