name: Reusable Deploy Workflow
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true
   
jobs:
  deployment:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: prepare
      run: echo ${{ inputs.username }} invoke deployment for ${{ inputs.environment }}
    - name: invoke deployment
      run: echo ${{ inputs.environment }} completed!
               
