name: Trigger Repository Dispatch
on: repository_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run |
          curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          "https://api.github.com/repos/${{ github.actor }}/${{ github.repository }}/dispatches" \
          -d '{"event_type": "awesomeness", "client_payload": {"foo": "bar"}}'