name: Try-Catch-Finally
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello World'
    - id: fail_expected
      run: exit 1
    - name: Failure Handler
      id: failure_handler
      if: failure()
      run: echo 'Handled Error'
    - name: Retry
      if: ${{ failure() && steps.fail_expected.conclusion == 'failure' }}
      run: echo 'I'm good now'
    - name: always
      if: always()
      run: |
        echo '${{ steps.fail_expected.conclusion}}'
        echo '${{ steps.failure_handler.conclusion}}'
        echo 'I will run always'
