name: Try-Catch-Finally
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello World'
    - run: exit 1
    - name: Failure Handler
      if: failure()
      run: echo 'Handled Error'
    - name: Retry
      if: success()
      run: echo 'I'm good now'
    - name: always
      if: always()
      run: echo 'I will run always'
