name: Reusable matrix workflow

on:
  workflow_dispatch:
jobs:
  deploy:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      username: ${{ github.actor }}
      environment: ${{ matrix.target }}
