name: Use Of Reusable Workflow 1

on:
  workflow_dispatch:
    inputs:
      dockerImage:
        type: string
        required: true
        default: 'ghcr.io/org/todo'
      dockerImageVersion:
        type: string
        required: false
        default: 'latest'
      deployEnvironment:
        type: environment
        required: true
        default: 'dev-preprod'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo build
  deploy:
    needs: build
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      dockerImage: ${{ inputs.dockerImage }}
      dockerImageVersion: ${{ inputs.dockerImageVersion }}
      deployEnvironment: ${{ inputs.deployEnvironment }}
