name: WorkFlowTwo

on:
  schedule:
  - cron: '10 * * * *'
    
  workflow_run:
    workflows: [ "WorkFlowOne" ]
    branches: [ main ]
    types: [ completed ]

  workflow_dispatch:
 
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: StepOne
        run: | 
            echo "Hello"
