name: WorkFlowTwo

on:
  workflow_run:
    workflows: [ "WorkFlowOne" ]
    branches: [ main ]
    types: [ completed ]

  workflow_dispatch:
 
jobs:
  termination:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Stop
        run: |
          echo "Stop has been invoked"
