name: WorkFlowTwo

on:
  schedule:
  - cron: ${{ inputs.cron }}
    
  workflow_run:
    workflows: [ "WorkFlowOne" ]
    branches: [ main ]
    types: [ completed ]

  workflow_dispatch:
    inputs:
      cron:
        description: 'Schedule the Job'
        default: '10 * * * *'
        required: true
        type: string
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: StepOne
        run: | 
            echo "Hello"