name: On Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: |
          echo  The logLevel is ${{ inputs.logLevel }} 
          echo  The print_tags are ${{ inputs.print_tags }}
          echo  The tags are ${{ inputs.tags }}
          echo  The environment are ${{ inputs.environment }}
  will-print-inputs:
    runs-on: ubuntu-latest
    if: inputs.print_tags
    steps:
    - run: |
         echo  The print_tags are ${{ inputs.print_tags }}
