name: Useful Of Reusable Workflow
on:
 workflow_dispatch:
jobs:
  username-samit:
    uses: ./.github/workflows/on_workflow_call.yaml
    with:
      username: SAMIT
    secrets: inherit
  username-other:
    uses: ./.github/workflows/on_workflow_call.yaml
    with:
      username: OTHER
    secrets: inherit
